Bloggie.Web/Controllers/AdminBlogPostsController.cs
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Bloggie.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminBlogPostsController : Controller
    {
        private readonly ITagRepository tagRepository;
        private readonly IBlogPostRepository blogPostRepository;

        //Here we are using Repository methods inside controller to talk to DB insted of DbContext

        //Injecting TagRepository and BlogPostRepository
        public AdminBlogPostsController(ITagRepository tagRepository, IBlogPostRepository blogPostRepository)
        {
            this.tagRepository = tagRepository;
            this.blogPostRepository = blogPostRepository;
        }
        //S1.Creating Asynchronous Add method to add new Blogs it is also a Index or home page for Add New BlogPost page
        //In this Add functionality we are fetching only Tags to display on Multiple dropdown selection to display on Add views page
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            // Talking to Repository to get tags from repository for displaying on multiple dropdown box inside add view
            var tags = await tagRepository.GetAllAsync();

            //after gettings tags from tagRepository we can assign tags to View Model AddBlogPostrequest
            //To fill Tags properties with Text as Name and value as Guid converted to string

            var model = new AddBlogPostRequest
            {
                Tags = tags.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() })
            };
            //providing this model to View for Model Binding
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Add(AddBlogPostRequest addBlogPostRequest)
        {
            //Based on the Id's comming from AddBlogpostRequest we can assign the Tags to Blogpost as below
            
            //Mapping properties of View Model to Domain Model before we post the values
            //Blogpost is the Domain Model and addBlogPostRequest is the View Model

            var blogPost = new BlogPost
            {
                Heading = addBlogPostRequest.Heading,
                PageTitle = addBlogPostRequest.PageTitle,
                Content = addBlogPostRequest.Content,
                ShortDescription = addBlogPostRequest.ShortDescription,
                FeaturedImageUrl = addBlogPostRequest.FeaturedImageUrl,
                UrlHandle = addBlogPostRequest.UrlHandle,
                PublishedDate = addBlogPostRequest.PublishedDate,
                Author = addBlogPostRequest.Author,
                Visible = addBlogPostRequest.Visible,
            };

            // Maping Tags property from selected tags by looping through ID and get the values from DB
            var selectedTags = new List<Tag>();
            foreach (var selectedTagId in addBlogPostRequest.SelectedTags)
            {
                var selectedTagIdAsGuid = Guid.Parse(selectedTagId);
                var existingTag = await tagRepository.GetAsync(selectedTagIdAsGuid);

                if (existingTag != null)
                {
                    selectedTags.Add(existingTag);
                }
            }

            // Mapping tags back to domain model
            blogPost.Tags = selectedTags;


            await blogPostRepository.AddAsync(blogPost);



            return RedirectToAction("Add"); //Here we can also redirect to List method to display list of all Blogpost
        }
        //S2.Working on List Action Method to Display all Blogs by fetching from DB models
        //[HttpGet]
        //public async Task<IActionResult> List()
        //{

        //    // Calling the repository to get back all the Blogs data from DB using blogPostrepository Injected file
        //    var blogPosts = await blogPostRepository.GetAllAsync();

        //    return View(blogPosts);
        //}

        //New code added here
        //S2.Working on above same List Action Method to Display all Blogs with Pagination
        [HttpGet]
        [ActionName("List")]
        public async Task<IActionResult> List(
            int pageSize = 2, //this is for displaying no of elements/Tags result in each page here I changed from 3 to 1
            int pageNumber = 1)
        {
            //To get the count of Tags Tag Repository has
            //Based on the count on subset of pages we need to return the result
            var totalRecords = await blogPostRepository.CountAsync();
            var totalPages = Math.Ceiling((decimal)totalRecords / pageSize);

            //If the page doesn't exit if no tags found on other pages then stick on same last page
            if (pageNumber > totalPages)
            {
                pageNumber--;
            }
            //If the page no is less then we can increase the page no to show all tags
            if (pageNumber < 1)
            {
                pageNumber++;
            }

            //This ViewBag is reposnsible for saving the input text to stay on the text field while searching
            ViewBag.TotalPages = totalPages;

            //To temporary save the state of searh Query we use ViewBag here and inside cshtml page list
            
            ViewBag.PageSize = pageSize;
            ViewBag.PageNumber = pageNumber;

            // use dbContext to read the tags based on searchQuery sorting and pagination
            var tags = await blogPostRepository.GetAllAsync(pageNumber, pageSize);

            return View(tags);
        }

        //New code ends here

        //Now to perform Edit operation first we need to get the single blogpost back based on Id and
        //then display one form with all the fileds to edit the Blogpost
        //S1.For Edit first displaying a single blogpost based on ID using Edit Action method and HttpGet keyword
        [HttpGet]
        //asp-route-id="@blogPost.Id" thish should match with the parameter of Edit(Guid id) below
        public async Task<IActionResult> Edit(Guid id)
        {
            // Retrieve the result like single blog information along with tags from the repository using blogpostRepository and tagRepository
            var blogPost = await blogPostRepository.GetAsync(id);
            var tagsDomainModel = await tagRepository.GetAllAsync();

            if (blogPost != null)
            {
                //mapping the domain model into the view model to show all fileds from DB model on web page for editing
                var model = new EditBlogPostRequest
                {
                    Id = blogPost.Id,
                    Heading = blogPost.Heading,
                    PageTitle = blogPost.PageTitle,
                    Content = blogPost.Content,
                    Author = blogPost.Author,
                    FeaturedImageUrl = blogPost.FeaturedImageUrl,
                    UrlHandle = blogPost.UrlHandle,
                    ShortDescription = blogPost.ShortDescription,
                    PublishedDate = blogPost.PublishedDate,
                    Visible = blogPost.Visible,
                    //After getting all Tags we have to show it as a dropdown Selection list
                    //So converting tagsDomain in to dropdown select list using select Linq method
                    Tags = tagsDomainModel.Select(x => new SelectListItem
                    {
                        //Setting properties for object
                        Text = x.Name,
                        Value = x.Id.ToString()
                    }),
                    SelectedTags = blogPost.Tags.Select(x => x.Id.ToString()).ToArray()
                };

                return View(model);

            }

            // pass data to view
            return View(null);
        }
        //S2 for Editing like once user fills the properties again it shoul update the DB models
        [HttpPost]
        public async Task<IActionResult> Edit(EditBlogPostRequest editBlogPostRequest)
        {
            // map view model back in to domain model to recieve the information
            var blogPostDomainModel = new BlogPost
            {
                Id = editBlogPostRequest.Id,
                Heading = editBlogPostRequest.Heading,
                PageTitle = editBlogPostRequest.PageTitle,
                Content = editBlogPostRequest.Content,
                Author = editBlogPostRequest.Author,
                ShortDescription = editBlogPostRequest.ShortDescription,
                FeaturedImageUrl = editBlogPostRequest.FeaturedImageUrl,
                PublishedDate = editBlogPostRequest.PublishedDate,
                UrlHandle = editBlogPostRequest.UrlHandle,
                Visible = editBlogPostRequest.Visible
            };

            // Mapping tags into domain model which is for navigation property

            var selectedTags = new List<Tag>();
            foreach (var selectedTag in editBlogPostRequest.SelectedTags)
            {
                if (Guid.TryParse(selectedTag, out var tag))
                {
                    var foundTag = await tagRepository.GetAsync(tag);

                    if (foundTag != null)
                    {
                        selectedTags.Add(foundTag);
                    }
                }
            }

            blogPostDomainModel.Tags = selectedTags;

            // Submit information to repository to update
            var updatedBlog = await blogPostRepository.UpdateAsync(blogPostDomainModel);

            if (updatedBlog != null)
            {
                // Show success notification and redirect to Edit HttpGet action method
                return RedirectToAction("List");
            }

            // Show error notification
            return RedirectToAction("Edit");
        }

Bloggie.Web/Views/AdminBlogPosts/Add.cshtml
@model Bloggie.Web.Models.ViewModels.AddBlogPostRequest

@*
First line should be for model binding    
This is the Add View/Index page for AdminBlogPost Controller Add Action method to add new blogs
*@

@{
}


<!--S1.This is the view page for adding new blogs with Heading-->
<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Add New BlogPost - Admin Functionality</h1>
    </div>
</div>
<!--S2.Creating a Form to accept the input fileds data like heading,..for adding new blogs
    asp-for is for model binding from models/ViewModels/AddBlogpostRequest.cs
    based on each properties of Add we will create all input elements here using asp-for
-->
<div class="container py-5">
    <form method="post">

        <div class="mb-3">
            <label class="form-label">Heading</label>
            <input type="text" class="form-control" id="heading" asp-for="Heading" />
        </div>

        <div class="mb-3">
            <label class="form-label">Page Title</label>
            <input type="text" class="form-control" id="pageTitle" asp-for="PageTitle" />
        </div>

        <div class="mb-3">
            <label class="form-label">Content</label>
            <textarea class="form-control" id="content" asp-for="Content"></textarea>
        </div>

        <div class="mb-3">
            <label class="form-label">Short Description</label>
            <input type="text" class="form-control" id="shortDescription" asp-for="ShortDescription" />
        </div>

        <div class="mb-3">
            <label class="form-label">Featured Image Upload</label>
            <input type="file" id="featuredImageUpload" class="form-control" />

            <img src="" id="featuredImageDisplay" style="display:none;width: 300px;" />
        </div>

        <div class="mb-3">
            <label class="form-label">Featured Image URL</label>
            <input type="text" class="form-control" id="featuredImageUrl" asp-for="FeaturedImageUrl" />
        </div>

        <div class="mb-3">
            <label class="form-label">URL Handle</label>
            <input type="text" class="form-control" id="urlHandle" asp-for="UrlHandle" />
        </div>

        <div class="mb-3">
            <label class="form-label">Published Date</label>
            <input type="date" class="form-control" id="publishedDate" asp-for="PublishedDate" />
        </div>

        <div class="mb-3">
            <label class="form-label">Author</label>
            <input type="text" class="form-control" id="author" asp-for="Author" />
        </div>

        <div class="form-check mb-3">
            <input class="form-check-input" type="checkbox" id="visible" asp-for="Visible">
            <label class="form-check-label">
                Is Visible?
            </label>
        </div>

        <div class="mb-3">
            <label class="form-label">Tags</label>
            <select class="form-select"
                    asp-items="@Model.Tags"
                    asp-for="SelectedTags">
            </select>
        </div>


        <div class="mb-3">
            <button type="submit" class="btn btn-dark">
                Save
            </button>
        </div>


    </form>
</div>


@section Scripts {
    <script>
        var editor = new FroalaEditor('#content', {
            imageUploadURL: '/api/images'
        });


        const featuredUploadElement = document.getElementById('featuredImageUpload');
        const featuredImageUrlElement = document.getElementById('featuredImageUrl');
        const featuredImageDisplayElement = document.getElementById('featuredImageDisplay');


        async function uploadFeaturedImage(e) {
            console.log(e.target.files[0]);

            let data = new FormData();
            data.append('file', e.target.files[0]);

            await fetch('/api/images', {
                method: 'POST',
                headers: {
                    'Aceept': '*/*',
                },
                body: data
            }).then(response => response.json())
                .then(result => {
                    featuredImageUrlElement.value = result.link;
                    featuredImageDisplayElement.src = result.link;
                    featuredImageDisplayElement.style.display = 'block';
                });
        }


        featuredUploadElement.addEventListener('change', uploadFeaturedImage);

    </script>
}

Bloggie.Web/Views/AdminBlogPosts/Edit.cshtml
@model Bloggie.Web.Models.ViewModels.EditBlogPostRequest

@*
    This is the view for Edit and Delete
*@
@{
}
﻿

@{
}

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Edit BlogPost - Admin Functionality</h1>
    </div>
</div>

<div class="container py-5">
    @if (Model != null)
    {
        <form method="post">

            <div class="mb-3">
                <label class="form-label">Id</label>
                <input type="text" class="form-control" id="id" asp-for="Id" readonly />
            </div>

            <div class="mb-3">
                <label class="form-label">Heading</label>
                <input type="text" class="form-control" id="heading" asp-for="Heading" />
            </div>

            <div class="mb-3">
                <label class="form-label">Page Title</label>
                <input type="text" class="form-control" id="pageTitle" asp-for="PageTitle" />
            </div>

            <div class="mb-3">
                <label class="form-label">Content</label>
                <textarea class="form-control" id="content" asp-for="Content"></textarea>
            </div>

            <div class="mb-3">
                <label class="form-label">Short Description</label>
                <input type="text" class="form-control" id="shortDescription" asp-for="ShortDescription" />
            </div>

            <div class="mb-3">
                <label class="form-label">Featured Image Upload</label>
                <input type="file" id="featuredImageUpload" class="form-control" />

                @if (Model.FeaturedImageUrl != null)
                {
                    <img src="@Model.FeaturedImageUrl" id="featuredImageDisplay" style="display:block;width: 300px;" />
                }
                else
                {
                    <img src="" id="featuredImageDisplay" style="display:none;width: 300px;" />
                }
            </div>

            <div class="mb-3">
                <label class="form-label">Featured Image URL</label>
                <input type="text" class="form-control" id="featuredImageUrl" asp-for="FeaturedImageUrl" />
            </div>

            <div class="mb-3">
                <label class="form-label">URL Handle</label>
                <input type="text" class="form-control" id="urlHandle" asp-for="UrlHandle" />
            </div>

            <div class="mb-3">
                <label class="form-label">Published Date</label>
                <input type="date" class="form-control" id="publishedDate" asp-for="PublishedDate" />
            </div>

            <div class="mb-3">
                <label class="form-label">Author</label>
                <input type="text" class="form-control" id="author" asp-for="Author" />
            </div>

            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" id="visible" asp-for="Visible">
                <label class="form-check-label">
                    Is Visible?
                </label>
            </div>

            <div class="mb-3">
                <label class="form-label">Tags</label>
                <select class="form-select"
                        asp-items="@Model.Tags"
                        asp-for="SelectedTags">
                </select>
            </div>

            <div class="mb-3 d-flex">
                <button type="submit" class="btn btn-dark">Update</button>

                <button type="submit"
                        class="btn btn-danger ms-2"
                        asp-area=""
                        asp-controller="AdminBlogPosts"
                        asp-action="Delete">
                    Delete
                </button>
            </div>

        </form>
    }

    else
    {
        <p>No blog post found!</p>

    }


</div>


@section Scripts {
    <script>
        var editor = new FroalaEditor('#content', {
            imageUploadURL: '/api/images'
        });


        const featuredUploadElement = document.getElementById('featuredImageUpload');
        const featuredImageUrlElement = document.getElementById('featuredImageUrl');
        const featuredImageDisplayElement = document.getElementById('featuredImageDisplay');


        async function uploadFeaturedImage(e) {
            console.log(e.target.files[0]);

            let data = new FormData();
            data.append('file', e.target.files[0]);

            await fetch('/api/images', {
                method: 'POST',
                headers: {
                    'Aceept': '*/*',
                },
                body: data
            }).then(response => response.json())
                .then(result => {
                    featuredImageUrlElement.value = result.link;
                    featuredImageDisplayElement.src = result.link;
                    featuredImageDisplayElement.style.display = 'block';
                });
        }


        featuredUploadElement.addEventListener('change', uploadFeaturedImage);


    </script>
}

Bloggie.Web/Views/AdminBlogPosts/List.cshtml
@model List<Bloggie.Web.Models.Domain.BlogPost>

@*
First line should be for model binding    
This is the List View page to display all Blogs inside a Bootstrap Table for AdminBlogPost Controller Add Action method List all blogs
*@

@{
}

@{
    int nextPage = Convert.ToInt32(ViewBag.PageNumber) + 1;
    int prevPage = Convert.ToInt32(ViewBag.PageNumber) - 1;
}

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>All BlogPosts - Admin Functionality</h1>
    </div>
</div>




<!--Creating a Bootstrap Table to list all the Blogs inside a table-->

<div class="container py-5">
     @if (Model != null && Model.Any())
    {
    
        <table class="table">
            <thead>
                <tr>
                    <td>Id</td>
                    <td>Heading</td>

                    <td>Tags

                        


                    </td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var blogPost in Model)
                {
                    <tr>
                        <!--Displaying two columns here-->
                        <td>@blogPost.Id</td>
                        <td>@blogPost.Heading</td>
                        <td>
                            <!--To fetch all tags related to each Blog and display beside Heading in next column
                                by looping on all the Blogpost Tags-->
                            
                            <div class="d-flex">
                                @foreach (var tag in blogPost.Tags)
                                {
                                    <span class="badge bg-secondary me-1">@tag.Name</span>
                                }
                            </div>
                        </td>

                        <!--Below TD is to show Edit option for each blogpost-->
                        <td>
                            <a asp-area=""
                               asp-controller="AdminBlogPosts"
                               asp-action="Edit"
                               asp-route-id="@blogPost.Id">
                                Edit
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <!--Below is for Pagination functionality dividing contents based on pages-->
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item">
                    <a class="page-link"
                       asp-controller="AdminBlogPosts"
                       asp-action="List"
                       asp-route-pageNumber="@prevPage"
                       asp-route-pageSize="@ViewBag.PageSize"
                       asp-route-sortBy="@ViewBag.SortBy"
                       asp-route-sortDirection="@ViewBag.SortDirection">
                        Previous
                    </a>
                </li>

                @for (int i = 1; i <= ViewBag.TotalPages; i++)
                {
                    <li class="page-item">
                        <a class="page-link"
                           asp-controller="AdminBlogPosts"
                           asp-action="List"
                           asp-route-pageNumber="@i"
                           asp-route-pageSize="@ViewBag.PageSize"
                           asp-route-sortBy="@ViewBag.SortBy"
                           asp-route-sortDirection="@ViewBag.SortDirection">
                            @i
                        </a>
                    </li>
                }


                <li class="page-item">
                    <a class="page-link"
                       asp-controller="AdminBlogPosts"
                       asp-action="List"
                       asp-route-pageNumber="@nextPage"
                       asp-route-pageSize="@ViewBag.PageSize"
>
                        Next
                    </a>
                </li>
            </ul>
        </nav>


    
    }
    else 
    {
        <p>No Blog Posts Found!</p>
    }

</div>